name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    env:
      github_sha: ${{ github.sha }}
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/clean_k9_data:latest --tag islasgeci/clean_k9_data:${github_sha:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci make check
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login -u "${docker_username}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/clean_k9_data:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/clean_k9_data:${github_sha:0:4}

